### ISSUE TITLE
round trip (unparse) back to code?

### ISSUE THREAD

**Issue by rrhg** [t3rn0/ast-comments#6]
Not an issue nor feature request.  Just asking if there's an easy way to convert the tree back to code without using other libraries for parsing.
I tried:
`ast_comments.unparse(tree)` 
`ast.unparse(tree)` 
`astor.to_source(tree)`
All of them work but comments are missing in the final code.

**Comment by t3rn0** [comment]
It seems to be the right feature for `ast_comments`

We'll have to separate inline comments from regular ones. Not doing so will probably break some compatibility with static analysis tools (mypy, pylint, ...)

**Comment by t3rn0** [comment]
@rrhg can you give examples of when this functionality would be useful?

**Comment by hippocritical** [comment]
You asked for an example so here is mine :
I want to update the code of freqtrade strategies (python files) from IStrategy-v2 to IStrategy-v3 and ast itself does not include comments that's why the updater would be impossible.
Astor itself does neither include the comments.
ast_comments would be the perfect fit, but why does it now allow unparsing when you are allowed to parse?

Without the option to unparse this solution will be non-working since I cannot produce any code back to a file.

Honestly, why is this not a thing? If there is a program to parse, why not unparse?
I would see no benefit in preserving comments if you cannot unparse those comments again after changing the code in ast_comments.

**Comment by t3rn0** [comment]
Well, initially I wanted to use it for some static code analysis.
That's why my focus was on parsing code only. Plus, I chose (almost randomly) python3.8 as the minimum supported version. And there is no `ast.unparse` in python3.8

But I agree: `ast_comments` should be expected to preserve comments when unparsing ast back into the code.

Here are some thoughts:
1. No `ast.unparse` in python3.8. Not a big problem but something we have to deal with.

2. Some static analysis tools are sensitive to where you put your comments.
```
a = 1 # comment

## or

# some comment
a = 1
```
So in order to put the comment in the right place when unparsing, we have to save some extra information (`inline: bool`)

3. Comments depend on statement nodes
```
# this comment will be stored
a = 1

# this comment will be lost because there is no statement below
```
If we're doing this enhancement, we would expect that all comments will be there after unparsing.
Current solution assumes in its core, that comments are going to be stored in the ast only if they relate to some tree node.
No statement nodes, no comments in the parsed tree.

To make this work I think we have to change this general assumption and:
- remove `comments` attribute from statement nodes
- store comments (or whole comments-blocks) in some comment-specific nodes
- doing so we solve the first issue because now we have the whole comment node with its value and position

```
>>> source = """
... # comment 1
... a = 1
... 
... # comment 2
>>> """
>>> print(astcom.dump(astcom.parse(source), indent=" "))
Module(
 body=[
  Comment(value='comment 1', ...),
  Assign(...),
  Comment(value='comment 2', ...),
 ], 
 ...
)
```

**Comment by rrhg** [comment]
I don't know how often this feature is required. We could analyze questions in Stackoverflow like [this one](https://stackoverflow.com/questions/768634/parse-a-py-file-read-the-ast-modify-it-then-write-back-the-modified-source-c), which has a decent history.

I'm working in a PR for [Soorgeon](https://github.com/ploomber/soorgeon). They use [parso](https://parso.readthedocs.io/en/latest/index.html). One of the reasons is because it supports round-trip, but is a pain if you want to modify the tree.

**Comment by hippocritical** [comment]
hey, any updates?
The (my) code is working with ast/astor and just currently is ugly (no pretty-code option) and removes the comments.
I would really not like to reprogram the already working code updater and start all over with parso (which you already pointed out will be a pain to edit code)

**Comment by t3rn0** [comment]
Well, I'm working on it but the process/progress is very slow. I'm not sure that some new version of the library will be available in the following few weeks.
Turned out that there are many corner cases which are nearly impossible to deal with. Right now I decided to make no difference between regular and inline comments. Also there are things like (elif, else, except, finally) and I have no clue what to do with them :)
I believe there's simple solution somewhere but couldn't find it yet

**Comment by rrhg** [comment]
Seems like you are not the only one having problems with if statements. Take a look at [if's are unparsed inconsistently to ast.unparse, which breaks tests of the libs using astunparse.unparse as a fallback impl. #66 ](https://github.com/simonpercivall/astunparse/issues/66)

**Comment by hippocritical** [comment]
thanks @t3rn0 ! will wait patiently :)

**Comment by t3rn0** [comment]
So I've made this PR. Could you look at it? It would be great to have comments before the merge's done

**Comment by hippocritical** [comment]
will dive into it at the weekend

**Comment by hippocritical** [comment]
```
    tree = ast_comments.parse(code)
  File "[baseFolder]/.env/lib/python3.8/site-packages/ast_comments.py", line 19, in parse
    _enrich(source, tree)
  File "[baseFolder]/.env/lib/python3.8/site-packages/ast_comments.py", line 47, in _enrich
    tree_intervals = _get_tree_intervals(tree)
  File "[baseFolder]/.env/lib/python3.8/site-packages/ast_comments.py", line 85, in _get_tree_intervals
    attr_intervals.append((*_get_interval(items), attr))
  File "[baseFolder]/.env/lib/python3.8/site-packages/ast_comments.py", line 99, in _get_interval
    for item in items:
TypeError: 'Subscript' object is not iterable

Process finished with exit code 1
```


file that was parsed:
https://github.com/iterativv/NostalgiaForInfinity/releases/tag/v7.7.2
=> NostalgiaForInfinityNext.py

The error happened in row 3820 and I added this to debug the code:
```

def _get_interval(items: List[ast.AST]) -> Tuple[int, int]:
    linenos, end_linenos = [], []
    if isinstance(items, ast.Subscript):
        print("STOP!")
```
just put a breakpoint on the "STOP" row and you get to that very case.
(chose that .py file since this is a very long one and in the old notation)

Basically this code snippet is the issue:
`    for i in range(period, len(df)):
        final_ub[i] = basic_ub[i] if (
            basic_ub[i] < final_ub[i - 1]
            or mavalue[i - 1] > final_ub[i - 1]) else final_ub[i - 1]
        final_lb[i] = basic_lb[i] if (
            basic_lb[i] > final_lb[i - 1]
            or mavalue[i - 1] < final_lb[i - 1]) else final_lb[i - 1]`

![grafik](https://user-images.githubusercontent.com/41228167/218211496-49238aa9-082b-48a7-b73a-883b3aae42a7.png)

**Comment by t3rn0** [comment]
Great example. Aside from initial non-iterable "Subscript" problem, found another related to multiline expressions
Hopefully fixed them both

**Comment by hippocritical** [comment]
![grafik](https://user-images.githubusercontent.com/41228167/218280922-47f0aff9-918c-4bc5-9866-daf9fb519c49.png)
why would it turn if ... elif into if else if?
Just curious, else ... it works and didnt complain about the code being wrong.
The code looks funny with about 50+ if => else => if => else tabs
that issue will likely be the killer argument for the people having their strategies changed like that since it alters the structure itself and they won't like it.

**Comment by hippocritical** [comment]
Well on the other hand this has to be ast itself being the issue.
Your comments are working like a charm!

**Comment by t3rn0** [comment]
Cool! Then I'm merging it
There is some logic within `ast._Unparser.visit_If` method. I'll try to do something with it but in different PR

**Comment by hippocritical** [comment]
> 

ping me whenever you want me to check it out :heart:
